on:
  push:
    - main

stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  runs-on: ubuntu-latest
  
  users: action/checkout@v2
  
  users: actions/setup-python@v2
  
  with:
    python-version: '3.10'
  
  run: |
    make init

  run: |
    make test

  run: |
    make build